[package]
name = "adocParser"
version = "0.1.0"
edition = "2021"

[dependencies]

regex = "1.10"
reqwest = { version = "0.11", features = ["blocking", "json"] }
serde = { version = "1.0", features = ["derive"] }

